import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Abiturs from './component/abiturs'

const Admin: NextPage = () => {
    const [methodEducation, setMethodEducation] = useState('');
    const handleChange=async (e: { target: { value: any } })=>{
        await setMethodEducation(e.target.value);
        await console.log(methodEducation)
    }
    return (
        <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
            Личный кабинет администратора
            </h1>
            <div className={styles.grid}>
            <div className={styles.card}>
                <Abiturs/>
            </div>
            </div>
        </main>

        <footer className={styles.footer}>
            Приемная комиссия КГБ ПОУ ХКОТСО
        </footer>
        </div>
    )
}

export default Admin
