import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          КГБ ПОУ ХКОТСО
        </h1>

        <p className={styles.description}>
          Хотите получить среднее профессиональное образование?
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            Подать документы
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Приемная комиссия КГБ ПОУ ХКОТСО
      </footer>
    </div>
  )
}

export default Home
