import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Test: NextPage = () => {
    return (
        <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
            Выберите форму обучения
            </h1>

            <div className={styles.grid}>
            <a className={styles.card}>
                очное
            </a>
            <a className={styles.card}>
                заочное
            </a>
            </div>
        </main>

        <footer className={styles.footer}>
            Приемная комиссия КГБ ПОУ ХКОТСО
        </footer>
        </div>
    )
}

export default Test
